[auth]
[[auth.users]]
username = "zhouxiang"
password = "hr123456"

[[auth.users]]
username = "gylhr"
password = "hr123456"

[[auth.users]]
username = "fxglb"
password = "hr123456"

[[auth.users]]
username = "hyk"
password = "hr123456"

